### ISSUE TITLE
Item Preview clears Costume

### ISSUE THREAD

**Issue by DU1R** [TeraProxy/Cosplayer#13]
When I preview an item in my bags (Ctrl + Right-Click), whether it be a weapon or BP, and click the X when done my Costume item is removed and I show my normal armor. I'm not sure sure if any other items get removed as Cosplay is only providing a costume and mount appearance, but it doesn't clear my mount, just the costume.
On a side note, this led to an idea for a possible feature to lock a costume so you can't accidentally change it (i.e. cosplay lock/unlock) or even a save/load feature so you can easily swap between costumes if you multiple ones you like (i.e. cosplay save [outfit name] / load [outfit name]. If you take feature requests I'd like to submit those and if you would like me to make a separate ticket for those I will.

**Comment by TeraProxy** [comment]
Hm... that's probably because I am changing the costume when you put on a costume item normally. I didn't know the preview works in the same way but makes sense.
I could easily fix this by preventing the change on manual costume changing. Gotta look at the packet traffic to see if I can solve this in a more elegant way.

Multiple presets is a nice idea but the presets file could get very bulky over time. I'll think about it.

**Comment by TeraProxy** [comment]
I fixed this in the latest update. Your custom outfit will now be reapplied when starting to move after your item preview. 

The "S_PREVIEW_ITEM" opcode must be mapped. I just pushed it to meishu's tera-data and will ask Caali to add it to his whitelisted ones. (don't worry, I will still consider the saving feature)
