### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by sing123456** [TeraProxy/Cosplayer#5]
After returning to lobby, getting errors: 
Cannot set property "nametag" of undefined 
    at presetUpdate (location of module here\index.js)
    at Object.Cosplayer.ditch.hook. event [as calleback] (location of the module here\index.js)

P.s. I shortened them a bit xD

**Comment by TeraProxy** [comment]
Hey sing, sorry for the late answer. That was a temporary issue and should have been fixed a while ago. Happened due to a null pointer when Cosplayer is being used while no config file is present (happens on first use for example).

Let me know if you are still getting that error. I'll recheck it later today as well.

**Comment by TeraProxy** [comment]
Did a test with a fresh installation and it worked without problems. You might have an old version, my friend. Try to download the newest files and remove your old ones.

**Comment by sing123456** [comment]
I updated everything, downloaded everything again and did a fresh install, happens again. It's ok tho, i just reset tera and everything back to normal. Thank for an awesome mod. :)))
