### ISSUE TITLE
Support for current node.js (10.0)

### ISSUE THREAD

**Issue by piecemealcranky** [TeraProxy/Cosplayer#6]
Using Node JS ver 10.0 gives this error:

![image](https://user-images.githubusercontent.com/31316063/39934156-8ad83056-5577-11e8-80f6-f619c10b3aba.png)

Yes I still use this over the other alternatives >_<

**Comment by TeraProxy** [comment]
Hm... I'd have to recompile the mouse library. That will break the module for people with older node versions though. Gimme a few days to look into this and think about what's best.

**Comment by TeraProxy** [comment]
@piecemealcranky Until I find a solution for everyone, you can do the following btw:

1. Delete the "Cosplayer/node_modules" folder
2. Open a command prompt and type "npm install win-mouse"
3. You can delete the "Cosplayer/node_modules/nan" folder afterwards (because it's already present in the main node_module folder of tera-proxy

This will compile the needed dependency for your environment.

**Comment by piecemealcranky** [comment]
Much appreciated, will give this a shot!

**Comment by TeraProxy** [comment]
Just pushed the newest version (2.1.0) which now defaults to Node.JS 10. You should be fine now by simply using the new version.
Thanks for letting me know about this, I didn't know Caali's proxy was already using Node.JS 10.
